In [8]:
import os, sys
import pandas as pd

cwd = os.getcwd()
display(os.listdir(cwd))

['.ipynb_checkpoints',
 'ann_optimization.log',
 'check err met.ipynb',
 'check_tif.ipynb',
 'comparison_opti.ipynb',
 'CO_resample.ipynb',
 'create_dataset_comb.ipynb',
 'eval_results.ipynb',
 'FR0000045072_FOB_CNN_LSTM_optimization.log',
 'FR0000051807_20231005_TIF.parquet.gzip',
 'FR0000073272_FOB_CNN_optimization.log',
 'FR0000073272_OHLCV_CNN_LSTM_optimization.log',
 'FR0000073272_OHLCV_CNN_optimization.log',
 'FR0000073272_OHLCV_LSTM_optimization.log',
 'FR0000120321_FOB_CNN.parquet.gzip',
 'FR0000120321_FOB_CNN_LSTM.parquet.gzip',
 'FR0000120321_OHLCV_FOB_CNN.parquet.gzip',
 'FR0000120321_True.parquet.gzip',
 'FR0000120578_OHLCV_CNN.parquet.gzip',
 'FR0000120578_OHLCV_CNN_LSTM.parquet.gzip',
 'FR0000120578_OHLCV_LSTM.parquet.gzip',
 'FR0000120578_True.parquet.gzip',
 'FR0000120628_20231027_FO.parquet.gzip',
 'FR0000120644_OHLCV_FOB_CNN_LSTM_optimization.log',
 'FR0000121485_OHLCV_CNN_LSTM_optimization.log',
 'FR001400AJ45_20231009_LOB.parquet.gzip',
 'FR001400AJ45_20231027_CO.parquet.gzip',
 'LOB_resample.ipynb',
 'metrics.ipynb',
 'metrics_col.parquet.gzip',
 'metrics_row.parquet.gzip',
 'optuna.ipynb',
 'ReadMe',
 'test_CO.ipynb',
 'Untitled.ipynb',
 'visu_split.ipynb']

In [10]:
df = pd.read_parquet('FR0000120578_OHLCV_LSTM.parquet.gzip')
display(df)

,Target_1,Target_2,Target_3,Target_4,Target_5,Target_6,Target_7,Target_8,Target_9,Target_10,...,Target_91,Target_92,Target_93,Target_94,Target_95,Target_96,Target_97,Target_98,Target_99,Target_100
0,0.000046,-0.000797,0.000122,0.000335,-0.000637,0.000040,-0.000178,-0.000072,-0.000587,0.000991,...,-0.003175,-0.003179,-0.002958,-0.003339,-0.004119,-0.003432,-0.003681,-0.004827,-0.004881,-0.004991
1,0.000093,-0.000820,0.000028,0.000343,-0.000758,-0.000110,-0.000129,-0.000006,-0.000503,0.000992,...,-0.003272,-0.003152,-0.003065,-0.003469,-0.004237,-0.003553,-0.003780,-0.004772,-0.004970,-0.005042
2,0.000105,-0.000876,0.000048,0.000378,-0.000724,-0.000088,-0.000133,-0.000081,-0.000575,0.000997,...,-0.003305,-0.003321,-0.003061,-0.003493,-0.004319,-0.003818,-0.003815,-0.004804,-0.005030,-0.005127
3,0.000046,-0.000904,0.000021,0.000289,-0.000607,-0.000115,-0.000143,-0.000181,-0.000525,0.000919,...,-0.003369,-0.003374,-0.003165,-0.003573,-0.004423,-0.003900,-0.003887,-0.004802,-0.005100,-0.005299
4,0.000060,-0.000859,0.000087,0.000324,-0.000710,-0.000135,-0.000171,-0.000094,-0.000603,0.000989,...,-0.003618,-0.003297,-0.003127,-0.003573,-0.004437,-0.003923,-0.003953,-0.004814,-0.005167,-0.005324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,0.000272,-0.001053,0.000619,0.000378,-0.001144,0.000144,0.000186,-0.000132,-0.001073,0.001016,...,-0.006992,-0.006670,-0.006307,-0.006772,-0.008277,-0.007735,-0.007636,-0.008429,-0.009435,-0.009214
393,-0.000123,-0.000791,0.000434,0.000412,-0.001023,0.000384,0.000034,-0.000257,-0.000786,0.000933,...,-0.007529,-0.007175,-0.006376,-0.007120,-0.008262,-0.008044,-0.007896,-0.008460,-0.009460,-0.009453
394,-0.000121,-0.000578,0.000260,0.000464,-0.000817,0.000252,-0.000471,-0.000262,-0.000825,0.000880,...,-0.007616,-0.007697,-0.006608,-0.007391,-0.008463,-0.008516,-0.007983,-0.008261,-0.009725,-0.009702
395,-0.000205,-0.000876,0.000381,0.000510,-0.000949,0.000244,-0.000408,-0.000272,-0.000716,0.001216,...,-0.007721,-0.007992,-0.006752,-0.007766,-0.008633,-0.008643,-0.008105,-0.008770,-0.010012,-0.009732
396,0.000082,-0.000900,0.000321,0.000547,-0.000748,0.000075,-0.000166,-0.000258,-0.000810,0.001576,...,-0.007991,-0.008362,-0.007223,-0.008161,-0.008574,-0.008810,-0.008055,-0.009305,-0.009997,-0.010098

In [7]:
df = pd.read_parquet('FR0000120578_True.parquet.gzip')
display(df)

,Target_1,Target_2,Target_3,Target_4,Target_5,Target_6,Target_7,Target_8,Target_9,Target_10,...,Target_91,Target_92,Target_93,Target_94,Target_95,Target_96,Target_97,Target_98,Target_99,Target_100
0,0.0,-0.001431,-0.000511,-0.001022,-0.002044,-0.002248,-0.001124,0.000000,0.000715,0.001124,...,0.016554,0.016861,0.016452,0.018598,0.019824,0.018905,0.020131,0.020335,0.019722,0.019415
1,0.0,0.000921,0.000409,-0.000614,-0.000819,0.000307,0.001433,0.002149,0.002558,0.001637,...,0.018318,0.017908,0.020057,0.021285,0.020364,0.021592,0.021797,0.021183,0.020876,0.020978
2,0.0,-0.000511,-0.001534,-0.001738,-0.000613,0.000511,0.001227,0.001636,0.000716,0.001738,...,0.016972,0.019119,0.020346,0.019425,0.020652,0.020857,0.020243,0.019937,0.020039,0.019425
3,0.0,-0.001023,-0.001227,-0.000102,0.001023,0.001739,0.002148,0.001227,0.002250,0.002455,...,0.019640,0.020867,0.019947,0.021174,0.021379,0.020765,0.020458,0.020561,0.019947,0.019845
4,0.0,-0.000205,0.000922,0.002048,0.002765,0.003174,0.002253,0.003277,0.003481,0.003789,...,0.021913,0.020991,0.022220,0.022425,0.021810,0.021503,0.021606,0.020991,0.020889,0.022937
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,0.0,-0.002668,-0.000485,0.007156,0.005215,0.003881,0.003153,0.006307,0.006671,0.008247,...,0.020012,0.017708,0.018557,0.020133,0.020376,0.022195,0.022680,0.023044,0.021831,0.020497
393,0.0,0.002189,0.009850,0.007905,0.006567,0.005837,0.008999,0.009364,0.010945,0.013620,...,0.020430,0.021282,0.022863,0.023106,0.024930,0.025417,0.025781,0.024565,0.023228,0.023228
394,0.0,0.007645,0.005703,0.004368,0.003640,0.006795,0.007159,0.008737,0.011406,0.013591,...,0.019051,0.020629,0.020871,0.022691,0.023177,0.023541,0.022327,0.020993,0.020993,0.026210
395,0.0,-0.001927,-0.003251,-0.003974,-0.000843,-0.000482,0.001084,0.003733,0.005901,0.008189,...,0.012885,0.013126,0.014933,0.015414,0.015776,0.014571,0.013247,0.013247,0.018425,0.022038
396,0.0,-0.001327,-0.002051,0.001086,0.001448,0.003016,0.005671,0.007843,0.010135,0.010618,...,0.015082,0.016892,0.017375,0.017736,0.016530,0.015203,0.015203,0.020391,0.024011,0.026424

In [13]:
ls = [5,5]
lss = (ls[0],ls[0])
display(lss)

(5, 5)