In [2]:
import os, sys
import pandas as pd

cwd = os.getcwd()

path_data = os.path.join(os.path.dirname(cwd), 'data')
display(path_data)

'C:\\Users\\Utilisateur\\Desktop\\doctorat\\2. Recherche\\Article 1\\3. Python\\PhD_article_1\\data'

In [3]:
display(os.listdir(path_data))

['assets.csv', 'processed', 'raw']

In [25]:
df = pd.read_csv(os.path.join(path_data, 'assets.csv'), index_col=0, usecols=[0,1,2])
ls_data = ['OHLCV','FOB','OHLCV_FOB']
ls_model = ['CNN','LSTM','CNN_LSTM']
df['data'] = [ls_data] * len(df)
df['model'] = [ls_model] * len(df)
df['optimization'] = 0
df['process'] = False

df = df.explode(['data']).explode('model').reset_index(drop=True)
display(df)

             ISIN     RIC       data     model  optimization  process
0    FR0000073272  SAF.PA      OHLCV       CNN             0    False
1    FR0000073272  SAF.PA      OHLCV      LSTM             0    False
2    FR0000073272  SAF.PA      OHLCV  CNN_LSTM             0    False
3    FR0000073272  SAF.PA        FOB       CNN             0    False
4    FR0000073272  SAF.PA        FOB      LSTM             0    False
..            ...     ...        ...       ...           ...      ...
346  NL0000235190  AIR.PA        FOB      LSTM             0    False
347  NL0000235190  AIR.PA        FOB  CNN_LSTM             0    False
348  NL0000235190  AIR.PA  OHLCV_FOB       CNN             0    False
349  NL0000235190  AIR.PA  OHLCV_FOB      LSTM             0    False
350  NL0000235190  AIR.PA  OHLCV_FOB  CNN_LSTM             0    False

[351 rows x 6 columns]

In [26]:
df.to_csv(os.path.join(path_data, 'assets_DB.csv'))

In [27]:
display(pd.read_csv(os.path.join(path_data, 'assets_DB.csv')))

,Unnamed: 0,ISIN,RIC,data,model,optimization,process
0,0,FR0000073272,SAF.PA,OHLCV,CNN,0,False
1,1,FR0000073272,SAF.PA,OHLCV,LSTM,0,False
2,2,FR0000073272,SAF.PA,OHLCV,CNN_LSTM,0,False
3,3,FR0000073272,SAF.PA,FOB,CNN,0,False
4,4,FR0000073272,SAF.PA,FOB,LSTM,0,False
...,...,...,...,...,...,...,...
346,346,NL0000235190,AIR.PA,FOB,LSTM,0,False
347,347,NL0000235190,AIR.PA,FOB,CNN_LSTM,0,False
348,348,NL0000235190,AIR.PA,OHLCV_FOB,CNN,0,False
349,349,NL0000235190,AIR.PA,OHLCV_FOB,LSTM,0,False
350,350,NL0000235190,AIR.PA,OHLCV_FOB,CNN_LSTM,0,False

In [30]:
display([c for c in df.columns if 'opti' in c])

['optimization']