In [10]:
import os, sys
import pandas as pd

cwd = os.getcwd()

display(os.listdir(cwd))

['.ipynb_checkpoints',
 'ann_optimization.log',
 'assets_DB.csv',
 'check err met.ipynb',
 'check_tif.ipynb',
 'comparison_opti.ipynb',
 'CO_resample.ipynb',
 'create_dataset_comb.ipynb',
 'eval_results.ipynb',
 'LOB_resample.ipynb',
 'metrics.ipynb',
 'optuna.ipynb',
 'ReadMe',
 'test_CO.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'visu_split.ipynb']

In [11]:
df = pd.read_csv('assets_DB.csv', index_col=0)
display(df)

             ISIN     RIC       data     model optimization  process
0    FR0000073272  SAF.PA      OHLCV       CNN            0    False
1    FR0000073272  SAF.PA      OHLCV      LSTM         True     True
2    FR0000073272  SAF.PA      OHLCV  CNN_LSTM         True     True
3    FR0000073272  SAF.PA        FOB       CNN            0    False
4    FR0000073272  SAF.PA        FOB      LSTM         True     True
..            ...     ...        ...       ...          ...      ...
346  NL0000235190  AIR.PA        FOB      LSTM            0    False
347  NL0000235190  AIR.PA        FOB  CNN_LSTM            0    False
348  NL0000235190  AIR.PA  OHLCV_FOB       CNN            0    False
349  NL0000235190  AIR.PA  OHLCV_FOB      LSTM            0    False
350  NL0000235190  AIR.PA  OHLCV_FOB  CNN_LSTM            0    False

[351 rows x 6 columns]

In [8]:
df.loc[df['model'] == 'CNN', 'optimization'] = 0
df.loc[df['model'] == 'CNN', 'process'] = False
display(df[df['model'] == 'CNN'])

             ISIN      RIC       data model optimization  process
0    FR0000073272   SAF.PA      OHLCV   CNN            0    False
3    FR0000073272   SAF.PA        FOB   CNN            0    False
6    FR0000073272   SAF.PA  OHLCV_FOB   CNN            0    False
9    FR0000120271  TTEF.PA      OHLCV   CNN            0    False
12   FR0000120271  TTEF.PA        FOB   CNN            0    False
..            ...      ...        ...   ...          ...      ...
336  FR001400AJ45  MICP.PA        FOB   CNN            0    False
339  FR001400AJ45  MICP.PA  OHLCV_FOB   CNN            0    False
342  NL0000235190   AIR.PA      OHLCV   CNN            0    False
345  NL0000235190   AIR.PA        FOB   CNN            0    False
348  NL0000235190   AIR.PA  OHLCV_FOB   CNN            0    False

[117 rows x 6 columns]

In [9]:
df.to_csv('assets_DB.csv')